export default function TokushoPage() {
  return (
    <main>
      <h1>特定商取引法に基づく表記</h1>

      <table>
        <tbody>
          <tr>
            <th>販売業者</th>
            <td>HERO株式会社</td>
          </tr>
          <tr>
            <th>代表者</th>
            <td>山形 啓泰（YAMAGATA HIROYASU）</td>
          </tr>
          <tr>
            <th>所在地</th>
            <td>石川県金沢市京町20番41号</td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td>お問い合わせはLINEにてお願いします</td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td>お問い合わせはLINEにてお願いします</td>
          </tr>
          <tr>
            <th>サービス料金</th>
            <td>各サービスページをご確認ください</td>
          </tr>
          <tr>
            <th>料金以外の必要費用</th>
            <td>なし</td>
          </tr>
          <tr>
            <th>支払方法</th>
            <td>銀行振込（請求書払い）</td>
          </tr>
          <tr>
            <th>支払時期</th>
            <td>契約時にご案内します</td>
          </tr>
          <tr>
            <th>サービス提供時期</th>
            <td>契約後、別途ご案内します</td>
          </tr>
          <tr>
            <th>返品・キャンセル</th>
            <td>サービスの性質上、契約後のキャンセル・返金はお受けできません。詳細は契約時にご確認ください。</td>
          </tr>
        </tbody>
      </table>
    </main>
  )
}
